services:
  - type: web
    name: autisense
    env: python
    plan: free
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
